### ISSUE TITLE
Invalid JSON generated

### ISSUE THREAD

**Issue by facundoolano** [kjonnala/gsa_template#1]
The JSON format of the results have trailing commas on the "meta_tags" list, causing it to fail on JSON validators (for example, while trying to parse it in python).

**Comment by ssbarnea** [comment]
I see a merge being done, a long time ago, does this means that this bug is fixed and you just missed to close it?

I would really like to know if this solution is used in production and by how many. I had to request the team that owns GSA to add this and they asked me about the risks. In fact I am surprised that Google missed to provide a solution for this.

**Comment by kjonnala** [comment]
Yes I seem to have missed this merge. But can you please test again.
